import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowRight, Stamp } from "lucide-react";

function Shell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-white text-slate-900"><header className="border-b"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><Link href="/" className="flex items-center gap-2 font-bold text-[#1a3a6b]"><Stamp className="h-5 w-5"/>Stampelo</Link><nav className="flex gap-4 text-sm"><Link href="/templates">Templates</Link><Link href="/pricing">Pricing</Link><Link href="/editor"><Button size="sm">Create stamp</Button></Link></nav></div></header>{children}<footer className="mt-20 border-t bg-slate-950 py-10 text-slate-300"><div className="mx-auto max-w-6xl px-4 text-sm"><Link href="/templates">Templates</Link> · <Link href="/guides/what-is-a-digital-stamp">Guides</Link> · <Link href="/faq">FAQ</Link></div></footer></div>;
}
function Hero({title,intro}:{title:string;intro:string}){return <section className="bg-slate-50 py-16"><div className="mx-auto max-w-4xl px-4"><h1 className="text-4xl font-bold md:text-5xl">{title}</h1><p className="mt-6 text-lg leading-8 text-slate-600">{intro}</p></div></section>}
function StampPreview({label}:{label:string}){return <div className="flex h-48 items-center justify-center rounded-xl border bg-white"><svg viewBox="0 0 220 130" className="h-36 w-52"><rect x="15" y="25" width="190" height="80" rx="7" fill="none" stroke="#1a3a6b" strokeWidth="5"/><rect x="24" y="34" width="172" height="62" rx="4" fill="none" stroke="#1a3a6b" strokeWidth="2"/><text x="110" y="73" textAnchor="middle" fill="#1a3a6b" fontSize="20" fontWeight="700">{label.toUpperCase()}</text></svg></div>}
function CTA(){return <div className="mt-8"><Link href="/editor"><Button className="gap-2">Customize in editor <ArrowRight className="h-4 w-4"/></Button></Link></div>}

export function StatusStampsPage(){const items=["Approved","Received","Paid","Confidential","Reviewed","Copy","Urgent","Filed"];return <Shell><Hero title="Status and workflow stamp templates" intro="Status stamps communicate a document state such as Approved, Received, Paid, Confidential, Reviewed or Filed. Stampelo groups these common administrative use cases in one category rather than creating pages for minor visual variations."/><main className="mx-auto max-w-6xl px-4 py-12"><div className="grid gap-5 md:grid-cols-4">{items.map(i=><Link href={`/templates/${i.toLowerCase()}-stamp`} key={i}><Card className="h-full"><CardContent className="p-4"><StampPreview label={i}/><h2 className="mt-4 font-bold">{i} stamp</h2></CardContent></Card></Link>)}</div><CTA/></main></Shell>}

function Individual({label,purpose,usage}:{label:string;purpose:string;usage:string[]}){return <Shell><Hero title={`${label} stamp template`} intro={purpose}/><main className="mx-auto max-w-5xl px-4 py-12"><div className="grid gap-8 md:grid-cols-2"><StampPreview label={label}/><div><h2 className="text-2xl font-bold">When this stamp is useful</h2><ul className="mt-5 space-y-3 text-slate-700">{usage.map(u=><li key={u}>• {u}</li>)}</ul><p className="mt-6 leading-7 text-slate-600">The template is a visual workflow aid. It does not by itself prove approval, payment, receipt, confidentiality or legal authority; organisations should apply their own document controls.</p><CTA/></div></div><div className="mt-12 rounded-xl bg-slate-50 p-6"><h2 className="font-bold">Related resources</h2><p className="mt-2 text-sm text-slate-600"><Link href="/templates/status-stamps" className="text-[#1a3a6b]">Status stamp templates</Link> · <Link href="/guides/what-is-a-digital-stamp" className="text-[#1a3a6b]">What is a digital stamp?</Link></p></div></main></Shell>}
export const ApprovedStampPage=()=> <Individual label="Approved" purpose="Create an APPROVED stamp for internal review and document-status workflows. Customize the text, shape, colour, dimensions and supporting details in the Stampelo editor." usage={["Purchase or invoice approval workflows","Internal document review","Design or proof approval","Administrative sign-off labels"]}/>;
export const ReceivedStampPage=()=> <Individual label="Received" purpose="Create a RECEIVED stamp for incoming-document and record-management workflows. Add a department, reference or date area when your process requires it." usage={["Incoming mail and document logging","Invoice receipt workflows","Records administration","Department intake processes"]}/>;
export const PaidStampPage=()=> <Individual label="Paid" purpose="Create a PAID stamp for invoices, receipts and internal accounting workflows. The visual label should be used together with the organisation's actual payment records." usage={["Invoice processing","Receipt marking","Accounts-payable workflows","Internal payment-status documentation"]}/>;
export const ConfidentialStampPage=()=> <Individual label="Confidential" purpose="Create a CONFIDENTIAL stamp for documents that your organisation classifies for restricted handling. The visual stamp is a label and does not provide encryption or access control." usage={["Internal confidentiality labels","Restricted document handling","Draft or review workflows","Administrative classification"]}/>;

export function DigitalVsRubberGuidePage(){return <Shell><Hero title="Digital stamp vs. rubber stamp" intro="Digital and physical rubber stamps can use similar designs, but they differ in how they are applied, stored and reused."/><main className="mx-auto max-w-5xl px-4 py-12"><div className="grid gap-6 md:grid-cols-2"><Card><CardContent className="p-6"><h2 className="text-2xl font-bold">Digital stamp</h2><p className="mt-4 leading-7 text-slate-600">A digital stamp is an image or vector element placed into an electronic document. It can be reused without ink and exported in formats such as PNG, SVG, EPS or PDF.</p></CardContent></Card><Card><CardContent className="p-6"><h2 className="text-2xl font-bold">Rubber stamp</h2><p className="mt-4 leading-7 text-slate-600">A physical rubber stamp transfers ink to paper. Its plate is manufactured as a physical object and typically has a fixed design until the plate is replaced.</p></CardContent></Card></div><h2 className="mt-10 text-2xl font-bold">Which should you use?</h2><p className="mt-4 leading-7 text-slate-600">Use the format required by the actual workflow. A visual digital stamp is convenient for electronic documents, while a physical stamp remains useful where paper processes require ink. Neither should be confused with a qualified electronic signature.</p><CTA/></main></Shell>}

export function ShapeGuidePage(){return <Shell><Hero title="Round vs. rectangular vs. oval stamp designs" intro="Stamp shape changes the available text layout and visual emphasis. The best shape depends on the information you need to fit and the document workflow."/><main className="mx-auto max-w-6xl px-4 py-12"><div className="grid gap-5 md:grid-cols-3">{[["Round","Company seals, curved text and symmetric layouts"],["Rectangular","Approval, received, paid, address and workflow labels"],["Oval","Seal-style designs that need more horizontal space"]].map(([shape,use])=><Card key={shape}><CardContent className="p-6"><h2 className="text-xl font-bold">{shape}</h2><p className="mt-3 leading-6 text-slate-600">{use}.</p></CardContent></Card>)}</div><p className="mt-8 leading-7 text-slate-600">Stampelo also supports triangular designs. Dimensions and text density should be adjusted so that the final stamp remains readable at the intended output size.</p><CTA/></main></Shell>}

export function TransparentPngGuidePage(){return <Shell><Hero title="How to create a transparent PNG stamp" intro="A transparent PNG keeps the stamp artwork while removing a solid page-colour background, making it easy to place the stamp over documents, slides or web content."/><main className="mx-auto max-w-4xl px-4 py-12"><h2 className="text-2xl font-bold">Why transparency matters</h2><p className="mt-4 leading-7 text-slate-600">A transparent background lets the document underneath remain visible around and inside the stamp design instead of adding a white rectangle around the image.</p><h2 className="mt-10 text-2xl font-bold">Steps</h2><ol className="mt-5 space-y-3 text-slate-700"><li>1. Create or select the stamp design.</li><li>2. Check the stamp colour and layout at the intended size.</li><li>3. Choose a PNG download package.</li><li>4. Download the transparent PNG.</li><li>5. Insert it into the target document or use the PDF Stamp Editor.</li></ol><CTA/></main></Shell>}
